<a href="https://colab.research.google.com/github/SydAt1/Eye_Disease_Classification/blob/main/notebooks/LR_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression Model

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns

## Data loading and Processing

In [ ]:
# LOAD DATA
df = pd.read_csv("prepped_NHIS_dataset.csv")

print("Dataset shape:", df.shape)
print("Risk level distribution:\n", df["Risk_Level"].value_counts())

Dataset shape: (11295, 10)
Risk level distribution:
 Risk_Level
0    5642
1    2856
2    1900
3     897
Name: count, dtype: int64

In [ ]:
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

,YearStart,Sex,RaceEthnicity,Question,Data_Value,RiskFactorID,RiskFactorResponseID,Age_range,Risk_Level
0,2016,0,6,8,2.74,0,5,2,0
1,2016,0,6,8,2.34,1,4,2,0
2,2016,0,6,8,5.25,1,6,2,0
3,2016,0,6,8,1.90,2,4,2,0
4,2016,0,6,8,4.02,2,6,2,0

### Feature Assigning and Test/Test Split

In [ ]:
# PREPARE FEATURES & TARGET
feature_cols = [col for col in df.columns if col not in ["Data_Value", "Risk_Level"]]

X = df[feature_cols]
y = df["Risk_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y  # IMPORTANT for class balance
)

In [ ]:
feature_cols

['YearStart',
 'Sex',
 'RaceEthnicity',
 'Question',
 'RiskFactorID',
 'RiskFactorResponseID',
 'Age_range']

## Training and Fitting Data into the Logistic Regression Pipeline

In [ ]:
logreg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        max_iter=1000,
        n_jobs=-1
    ))
])

logreg_pipeline.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()),
                ('logreg',
                 LogisticRegression(max_iter=1000, multi_class='multinomial',
                                    n_jobs=-1))])

In [ ]:
y_train_pred = logreg_pipeline.predict(X_train)
y_test_pred = logreg_pipeline.predict(X_test)

In [ ]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

## Evaluation Metrics

In [ ]:
# Performance Metrics

print(f"Training Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:     {test_acc:.4f}\n")

print("Classification Report (Test):")
print(classification_report(y_test, y_test_pred))

Training Accuracy: 0.6113
Test Accuracy:     0.6073

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.62      0.96      0.75      1693
           1       0.56      0.48      0.52       857
           2       0.84      0.05      0.09       570
           3       0.00      0.00      0.00       269

    accuracy                           0.61      3389
   macro avg       0.51      0.37      0.34      3389
weighted avg       0.59      0.61      0.52      3389

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

61% Accuracy, so lets try to up those numbers.

In [ ]:
logreg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        max_iter=3000,
        n_jobs=-1
    ))
])

logreg_pipeline.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()),
                ('logreg',
                 LogisticRegression(max_iter=3000, multi_class='multinomial',
                                    n_jobs=-1))])

In [ ]:
y_train_pred = logreg_pipeline.predict(X_train)
y_test_pred = logreg_pipeline.predict(X_test)

In [ ]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

In [ ]:
# Performance Metrics

print(f"Training Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:     {test_acc:.4f}\n")

print("Classification Report (Test):")
print(classification_report(y_test, y_test_pred))

Training Accuracy: 0.6113
Test Accuracy:     0.6073

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.62      0.96      0.75      1693
           1       0.56      0.48      0.52       857
           2       0.84      0.05      0.09       570
           3       0.00      0.00      0.00       269

    accuracy                           0.61      3389
   macro avg       0.51      0.37      0.34      3389
weighted avg       0.59      0.61      0.52      3389

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Hyperparamter Tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "logreg__C": [0.01, 0.1, 1, 3, 10]
}

GridSearchCV(
    logreg_pipeline,
    param_grid,
    scoring="balanced_accuracy",
    cv=5
)

grid.fit(X_train, y_train)

print("Best C:", grid.best_params_)
print("CV Accuracy:", grid.best_score_)

Best C: {'logreg__C': 3, 'logreg__class_weight': {0: 1, 1: 1.5, 2: 2.0}}
CV Accuracy: 0.40711821628842293

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [ ]:
logreg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        C=0.1,
        max_iter=2000,
        class_weight="balanced",
        solver="lbfgs",
        n_jobs=-1
    ))
])
logreg_pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('logreg',
                 LogisticRegression(C=0.1, class_weight='balanced',
                                    max_iter=2000, n_jobs=-1))])

In [ ]:
y_train_pred = logreg_pipeline.predict(X_train)
y_test_pred = logreg_pipeline.predict(X_test)

In [ ]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:     {test_acc:.4f}\n")

print("Classification Report (Test Set):")
print(classification_report(y_test, y_test_pred))

Training Accuracy: 0.5014
Test Accuracy:     0.4883

Classification Report (Test Set):
              precision    recall  f1-score   support

           0       0.68      0.57      0.62      1693
           1       0.56      0.55      0.55       857
           2       0.34      0.22      0.27       570
           3       0.12      0.36      0.18       269

    accuracy                           0.49      3389
   macro avg       0.43      0.42      0.41      3389
weighted avg       0.55      0.49      0.51      3389

### Define soft class weight candidates

In [ ]:
class_weight_grid = [
    {0:1, 1:1,   2:1,   3:1},      # baseline
    {0:1, 1:1.1, 2:1.2, 3:1.4},
    {0:1, 1:1.2, 2:1.4, 3:1.8},
    {0:1, 1:1.3, 2:1.6, 3:2.2},
    {0:1, 1:1.5, 2:2.0, 3:3.0},    # close to balanced
]

In [ ]:
param_grid = {
    "logreg__C": [0.1, 0.3, 1, 3],
    "logreg__class_weight": class_weight_grid
}

grid = GridSearchCV(
    logreg_pipeline,
    param_grid,
    scoring="balanced_accuracy",
    cv=5,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best CV balanced accuracy:", grid.best_score_)

Best params: {'logreg__C': 3, 'logreg__class_weight': {0: 1, 1: 1.5, 2: 2.0, 3: 3.0}}
Best CV balanced accuracy: 0.4124870885159185

### Evaluation with Tuned Hyperparameter

In [ ]:
best_pipeline = grid.best_estimator_

y_test_pred = best_pipeline.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

Test Accuracy: 0.6438477426969608
              precision    recall  f1-score   support

           0       0.68      0.94      0.79      1693
           1       0.56      0.66      0.61       857
           2       0.76      0.05      0.09       570
           3       0.00      0.00      0.00       269

    accuracy                           0.64      3389
   macro avg       0.50      0.41      0.37      3389
weighted avg       0.61      0.64      0.56      3389

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

The model has almost ignored the class "3" which is the high risk class.

Going to merge the 2 and 3 classes so we will have:

* 0 - Low risk

* 1 - Medium risk

* 2 - High risk

* 3 - High Risk (Merged with 2)

Initial experiments with four risk categories showed severe confusion between higher risk levels, particularly Risk_Level 2 and 3. As these categories represent similar clinical severity, they were merged into a single high-risk class, resulting in improved class balance and more reliable predictive performance.

In [ ]:
df["Risk_Level_3"] = df["Risk_Level"].replace({3: 2})

print(df["Risk_Level_3"].value_counts())

Risk_Level_3
0    5642
1    2856
2    2797
Name: count, dtype: int64

In [ ]:
X = df[feature_cols]
y = df["Risk_Level_3"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

In [ ]:
print(y_train.unique())
print(y_test.unique())

[0 1 2]
[1 0 2]

In [ ]:
class_weight = {
    0: 1,
    1: 1.2,
    2: 1.6
}

In [ ]:
logreg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        C=0.01,
        class_weight=class_weight,
        max_iter=4000,
        n_jobs=-1
    ))
])

logreg_pipeline.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()),
                ('logreg',
                 LogisticRegression(C=0.01, class_weight={0: 1, 1: 1.2, 2: 1.6},
                                    max_iter=4000, multi_class='multinomial',
                                    n_jobs=-1))])

In [ ]:
y_pred = logreg_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.624963115963411
              precision    recall  f1-score   support

           0       0.68      0.93      0.79      1693
           1       0.63      0.34      0.44       857
           2       0.40      0.29      0.34       839

    accuracy                           0.62      3389
   macro avg       0.57      0.52      0.52      3389
weighted avg       0.60      0.62      0.59      3389

[[1582   38   73]
 [ 265  289  303]
 [ 463  129  247]]

In [ ]:
class_weight_grid = [
    {0:1, 1:1,   2:1},     # no weighting
    {0:1, 1:1.1, 2:1.3},
    {0:1, 1:1.2, 2:1.6},
    {0:1, 1:1.3, 2:1.8},
    {0:1, 1:1.5, 2:2.0}
]

In [ ]:
param_grid = {
    "logreg__C": [0.1, 0.3, 1, 3, 5, 10],
    "logreg__class_weight": class_weight_grid
}

grid = GridSearchCV(
    logreg_pipeline,
    param_grid=param_grid,
    scoring="balanced_accuracy",
    cv=5,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best C:", grid.best_params_)
print("CV Accuracy:", grid.best_score_)

Best C: {'logreg__C': 5, 'logreg__class_weight': {0: 1, 1: 1.2, 2: 1.6}}
CV Accuracy: 0.5304622266032492

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [ ]:
logreg_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("logreg", LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        C=3,
        class_weight = {0: 1, 1: 1.1, 2: 1.3},
        n_jobs=-1
    ))
])

logreg_pipeline.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()),
                ('logreg',
                 LogisticRegression(C=3, class_weight={0: 1, 1: 1.1, 2: 1.3},
                                    multi_class='multinomial', n_jobs=-1))])

In [ ]:
y_pred = logreg_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6296842726467985
              precision    recall  f1-score   support

           0       0.65      0.95      0.77      1693
           1       0.61      0.40      0.49       857
           2       0.51      0.21      0.30       839

    accuracy                           0.63      3389
   macro avg       0.59      0.52      0.52      3389
weighted avg       0.61      0.63      0.58      3389

[[1613   53   27]
 [ 371  346  140]
 [ 494  170  175]]

Although Logistic Regression was carefully tuned using class weighting, regularization, and threshold adjustment, performance gains plateaued, particularly for higher risk classes. The inability of threshold calibration to improve recall without degrading overall performance suggests limited separability within a linear decision framework. As a result, Logistic Regression was considered to have reached its practical performance ceiling for this task, motivating the exploration of more expressive non-linear models

## Save the model (pipeline)

In [ ]:
import joblib

joblib.dump(logreg_pipeline, "logreg_3class_pipeline.pkl")

['logreg_3class_pipeline.pkl']

Use the following code later to use the model:

`y_pred = logreg_pipeline.predict(X_new)`

`y_proba = logreg_pipeline.predict_proba(X_new)`

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11295 entries, 0 to 11294
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   YearStart             11295 non-null  int64
 1   Sex                   11295 non-null  int64
 2   RaceEthnicity         11295 non-null  int64
 3   Question              11295 non-null  int64
 4   Data_Value            11295 non-null  float64
 5   RiskFactorID          11295 non-null  int64
 6   RiskFactorResponseID  11295 non-null  int64
 7   Age_range             11295 non-null  int64
 8   Risk_Level            11295 non-null  int64
 9   Risk_Level_3          11295 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 882.6 KB

In [ ]:
logreg_pipeline = joblib.load("logreg_3class_pipeline.pkl")

# Create new data with actual feature columns
X_new = pd.DataFrame({
    'YearStart': [2020],
    'Sex': [1],
    'RaceEthnicity': [2],
    'Question': [3],
    'RiskFactorID': [1],
    'RiskFactorResponseID': [2],
    'Age_range': [4]
})

# Make predictions
y_pred = logreg_pipeline.predict(X_new)
y_proba = logreg_pipeline.predict_proba(X_new)

print("Predicted Risk Level:", y_pred)  # 0=Low, 1=Medium, 2=High
print("Probabilities:", y_proba)

Predicted Risk Level: [1]
Probabilities: [[7.24665851e-06 9.99992699e-01 5.39202370e-08]]

In [ ]:
df.sample()

,YearStart,Sex,RaceEthnicity,Question,Data_Value,RiskFactorID,RiskFactorResponseID,Age_range,Risk_Level,Risk_Level_3
11249,2016,0,6,7,0.05,3,3,5,0,0